name = "Skeria"
license = "MIT"
licenselink = "https://github.com/dschrempf/skeria/LICENSE"
description = "An elegant open source and mobile first theme, extended with new integrations and layout improvements"
homepage = "https://github.com/dschrempf/skeria"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]
min_version = 0.14

[author]
    name = "Dominik Schrempf"
    homepage = "https://dschrempf.github.io/"

# If Porting existing theme
[original]
    author =  "poole"
    homepage = "http://hyde.getpoole.com"
    repo = "https://github.com/poole/hyde"
